# What is Categorical Data?

Categorical data represents labels or categories instead of numerical values.

Examples:
- Gender (Male, Female)
- Country (Nepal, India, USA)
- Species (Iris dataset)
- Day (Tips dataset)

Machine learning models cannot understand text categories directly.
They require numerical input.

# Why Encoding Categorical Data is Necessary

Encoding converts categorical values into numerical form so that:
- Machine learning models can process them
- Mathematical operations become possible
- Feature representation becomes meaningful

Without encoding, models will throw errors when encountering string values.

# Types of Categorical Data

1. Nominal Data:
- No inherent order
- Example: color, city, country

2. Ordinal Data:
- Has a meaningful order
- Example: low < medium < high

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# Load dataset containing categorical features (e.g., tips dataset)
# Identify categorical columns in the dataset
# Preview categorical data

tips = sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
cat_cols = tips.select_dtypes(include=['object', 'category', 'str']).columns
cat_cols

Index(['sex', 'smoker', 'day', 'time'], dtype='str')

## Label Encoding

Label Encoding is a categorical encoding technique that assigns a unique integer value to each category in a feature.  
It is simple, fast, and memory-efficient but may unintentionally introduce an ordinal relationship among categories.

### Example
City Feature:
- Kathmandu → 0  
- Pokhara → 1  
- Lalitpur → 2  

### When to Use
- Categorical variable is ordinal
- There is a natural order in categories
- Tree-based models (e.g., Decision Trees, Random Forest, XGBoost)
- Categorical features with many unique values
- Situations where memory efficiency is important

### Pros
- Simple and easy to implement  
- Memory-efficient compared to One-Hot Encoding  
- Works well with tree-based algorithms  

### Cons
- Introduces implicit ordering among categories  
- Can mislead models that assume numerical relationships (e.g., Linear Regression, KNN)  
- Not suitable for nominal data when used with non-tree models

In [4]:
# Import LabelEncoder from sklearn.preprocessing
# Initialize LabelEncoder
# Apply label encoding to categorical column
# Replace original categorical column with encoded values
from sklearn.preprocessing import LabelEncoder

data = ['Red', 'Green', 'Blue', 'Red', 'Green']

encoder = LabelEncoder()

encoded_data = encoder.fit_transform(data)
encoded_data

array([2, 1, 0, 2, 1])

In [5]:
data = pd.DataFrame({
    'Satisfaction': ['Low', 'High', 'Medium', 'Low', 'High'],
    'Score': [3, 8, 5, 2, 9]
})
satisfaction_order = {'Low': 0, 'Medium': 1, 'High': 2}
data['Satisfaction_Encoded'] = data['Satisfaction'].map(satisfaction_order)
print(data)

  Satisfaction  Score  Satisfaction_Encoded
0          Low      3                     0
1         High      8                     2
2       Medium      5                     1
3          Low      2                     0
4         High      9                     2

In [6]:
# Initialize LabelEncoder
le = LabelEncoder()

# Copy dataset for label encoding
tips_label = tips.copy()

# Apply label encoding to 'sex' column (example)
tips_label["sex_encoded"] = le.fit_transform(tips_label["sex"])

# View encoded results
tips_label[["sex", "sex_encoded"]].head()

      sex  sex_encoded
0  Female            0
1    Male            1
2    Male            1
3    Male            1
4  Female            0

In [8]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
tips_label_all = tips.copy()

# Apply label encoding to all categorical columns
for col in cat_cols:
    tips_label_all[col] = le.fit_transform(tips_label_all[col])

tips_label_all.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

# Limitations of Label Encoding

Problem:
Label encoding introduces artificial order between categories.

Example:
Red = 2, Blue = 0, Green = 1  
Model may assume Red > Green > Blue (which is incorrect for nominal data).

In [9]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
tips['smoker'].unique()

['No', 'Yes']
Categories (2, str): ['Yes', 'No']

smoker_yes | smoker_no

0 | 1
1 | 0

## One-Hot Encoding

One-Hot Encoding is a categorical encoding technique that converts each category into a separate binary column, where each column represents one category.  
It prevents the model from assuming any false order among categories.

### Example
Color Feature:
- Red → [1, 0, 0]  
- Blue → [0, 1, 0]  
- Green → [0, 0, 1]  

### When to Use
- Nominal (unordered) categorical features  
- Linear models and logistic regression  
- Number of categories is limited
- Neural networks and distance-based algorithms  
- Avoiding false ordinal relationships is important

### Pros
- Does not assume any ordinal relationship between categories  
- Widely supported in machine learning libraries  
- Easy to interpret  

### Cons
- Can lead to high dimensionality when there are many unique categories  
- Produces sparse data (many zeros)  
- Increases memory usage and computational cost for large datasets

In [13]:
# Use pandas get_dummies or OneHotEncoder from sklearn
# Apply one-hot encoding on categorical columns
# Create new dataframe with encoded features

tips_one_hot = pd.get_dummies(tips, columns = cat_cols)
tips_one_hot.head()

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,True,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,True,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,True,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,True,False,False,False,True,False,True

# Dummy Variable Trap

The Dummy Variable Trap occurs when one or more dummy variables created during One-Hot Encoding are highly correlated (multicollinearity).  
This happens when all categories of a categorical feature are encoded into separate binary columns, causing redundancy in the dataset.

### Why It Happens
If a categorical variable with \(k\) categories is converted into \(k\) dummy variables, the sum of all dummy columns will always equal 1.  
This creates perfect multicollinearity because one column can be predicted using the others.

### Example
Gender Feature:
- Male → [1, 0]  
- Female → [0, 1]  

Here:

Female = 1 − Male  

This means one variable is perfectly dependent on the other, leading to multicollinearity.

### Problems Caused
- Multicollinearity in regression models  
- Unstable coefficient estimates  
- Reduced model interpretability  
- Issues in Linear Regression and Logistic Regression  

### How to Avoid the Dummy Variable Trap
- Drop one dummy column (k-1 encoding)
- Use `drop_first=True` in One-Hot Encoding
- Use regularization techniques (Ridge/Lasso)
- Prefer tree-based models (less sensitive to multicollinearity)

### When It Matters Most
- Linear Regression  
- Logistic Regression  
- Any model sensitive to multicollinearity  

Tree-based models (e.g., Decision Trees, Random Forest) are generally not affected by the dummy variable trap.

In one-hot encoding, creating all category columns can cause multicollinearity.

Solution:
Drop one dummy column (drop_first = True)

In [14]:
# One-Hot Encoding with drop_first=True (recommended for ML models)
tips_onehot_drop = pd.get_dummies(tips, columns=cat_cols, drop_first=True)

tips_onehot_drop.head()

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16.99,1.01,2,True,True,False,False,True,True
1,10.34,1.66,3,False,True,False,False,True,True
2,21.01,3.50,3,False,True,False,False,True,True
3,23.68,3.31,2,False,True,False,False,True,True
4,24.59,3.61,4,True,True,False,False,True,True

In [15]:
print("Original Dataset Shape:", tips.shape)
print("After One-Hot Encoding Shape:", tips_one_hot.shape)
print("After One-Hot (drop_first) Shape:", tips_onehot_drop.shape)

Original Dataset Shape: (244, 7)
After One-Hot Encoding Shape: (244, 13)
After One-Hot (drop_first) Shape: (244, 9)

# Label Encoding vs One-Hot Encoding (Comparison)

Label Encoding:
- Simple and memory efficient
- Suitable for ordinal data
- Can introduce false order

One-Hot Encoding:
- No false ordering
- Suitable for nominal data
- Increases dimensionality

## Ordinal Encoding

Ordinal Encoding is a categorical encoding technique that converts categories into integer values while preserving their natural order.  
It is suitable for features where the categories have a meaningful ranking or hierarchy.

### Example
Education Level:
- High School → 1  
- Bachelor → 2  
- Master → 3  
- PhD → 4  

### When to Use
- Ordered categorical features (e.g., ratings, education levels, satisfaction levels)
- Features with a clear ranking or hierarchy

### Pros
- Maintains the natural order of categories  
- Reduces dimensionality compared to One-Hot Encoding  
- Simple and memory efficient  

### Cons
- Not suitable for nominal (unordered) categories  
- Model may assume equal distance between categories, which may not reflect reality  
- Can introduce unintended bias if order is incorrectly assigned

In [16]:
from sklearn.preprocessing import OrdinalEncoder
data = [['Low'], ['Medium'], ['High'], ['Medium'], ['Low']]

encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
encoded_data = encoder.fit_transform(data)

print(f"Encoded Ordinal Data: {encoded_data}")

Encoded Ordinal Data: [[0.]
 [1.]
 [2.]
 [1.]
 [0.]]

## Target Encoding (Mean Encoding)

Target Encoding, also known as Mean Encoding, is a categorical encoding technique where each category is replaced with the mean value of the target variable corresponding to that category.

This method incorporates target information into the encoding, making it especially useful for high-cardinality categorical features.

### Example
Category: Product ID  / Rating
- Product A → 0.75 (mean target value for A)  
- Product B → 0.42  
- Product C → 0.61  

### When to Use
- High-cardinality categorical features (e.g., ZIP codes, product IDs, user IDs)
- Supervised learning tasks where target variable is available
- Models where One-Hot Encoding would create too many columns

### Pros
- Captures the relationship between the category and the target variable  
- Reduces dimensionality compared to One-Hot Encoding  
- Effective for high-cardinality features  

### Cons
- High risk of overfitting if not handled properly  
- Requires techniques like smoothing, regularization, or cross-validation  
- Can introduce data leakage if applied before train-test split

In [ ]:
# !pip install category-encoders

In [19]:
import pandas as pd
import category_encoders as ce

df = pd.DataFrame(
    {'City': ['London', 'Paris', 'London', 'Berlin'], 'Target': [1, 0, 1, 0]}
)

encoder = ce.TargetEncoder(cols=['City'])
df_tgt = encoder.fit_transform(df['City'], df['Target'])

print(f"Encoded Target Data:\n{df_tgt}")

Encoded Target Data:
       City
0  0.570926
1  0.434946
2  0.570926
3  0.434946

## Frequency Encoding

Frequency Encoding is a categorical encoding technique that replaces each category with its frequency (count) or proportion of occurrence in the dataset.  
This provides a compact representation of categorical variables based on their popularity.

### Example
City Feature (Frequency):
- Kathmandu → 50  
- Pokhara → 30  
- Lalitpur → 20  

(Or as proportions: 0.50, 0.30, 0.20)

### When to Use
- High-cardinality categorical features  
- Retail, e-commerce, and clickstream data  
- Situations where category popularity carries useful information  

### Pros
- Low computational and storage requirements  
- Handles high-cardinality features efficiently  
- Simple to implement and interpret  

### Cons
- Can introduce data leakage if computed before train-test split  
- Does not capture relationship with the target variable  
- Different categories may receive similar frequencies, reducing separability

In [20]:
import pandas as pd
data = ['Red', 'Green', 'Blue', 'Red', 'Red']
series_data = pd.Series(data)
frequency_encoding = series_data.value_counts()

encoded_data = [frequency_encoding[x] for x in data]
print("Encoded Data:", encoded_data)

Encoded Data: [np.int64(3), np.int64(1), np.int64(1), np.int64(3), np.int64(3)]

# Real-World Preprocessing Pipeline Order

1. Handle Missing Values
2. Handle Outliers
3. Handle Skewness
4. Encoding Categorical Data
5. Feature Scaling
6. Model Training