## Why Data Cleaning?

Real-world data contains:
- Missing values
- Duplicate rows
- Incorrect values

Cleaning data is essential before analysis.

## Check For Missing Values 

Pandas provides the isna() and notna() functions to detect missing values, which work across different data types.

 These functions return a Boolean Series indicating the presence of missing values.

In [1]:
import pandas as pd

In [10]:
df_weather = pd.read_csv('/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/weather.csv', skiprows =1, header =0)
df_weather

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

In [11]:
df_weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          13 non-null     str
 1   temperature  13 non-null     str
 2   windspeed    13 non-null     str
 3   event        13 non-null     str
dtypes: str(4)
memory usage: 548.0 bytes

In [12]:
# Load dataset
path = '/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/weather.csv'
df_weather = pd.read_csv(path, skiprows=1, na_values={
    "temperature":['not available'],
    'windspeed': ['not measured'],
    'event': ['no event']
}
)
df_weather

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [13]:
# Detect missing values
df_weather.isnull()

      day  temperature  windspeed  event
0   False        False      False  False
1   False         True      False  False
2   False        False       True  False
3   False         True      False   True
4   False        False       True  False
5   False         True       True  False
6   False         True       True   True
7   False        False      False  False
8   False        False      False  False
9   False        False      False  False
10  False        False      False  False
11  False        False      False  False
12  False        False      False  False

In [15]:
# Count missing values per column
df_weather.isnull().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

In [16]:
df_weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          13 non-null     str
 1   temperature  9 non-null      float64
 2   windspeed    9 non-null      float64
 3   event        11 non-null     str
dtypes: float64(2), str(2)
memory usage: 548.0 bytes

Common strategies:
- Remove rows
    - `Note: By default, the dropna() method returns a new DataFrame, and will not change the original.`
    - If you want to change the original DataFrame, use the `inplace = True` argument
- Remove columns
- Fill missing values

In [17]:
df_weather

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [ ]:
# df_weather.dropna(inplace = True)

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [21]:
# Remove rows with missing values
drop_rows = df_weather.dropna()
drop_rows

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [ ]:
# Fill missing values with constant value
filled_constant = df_weather.fillna("unknown")
filled_constant

          day temperature windspeed    event
0    1/1/2017        32.0       6.0     Rain
1    1/4/2017     unknown       9.0    Sunny
2    1/5/2017        -1.0   unknown     Snow
3    1/6/2017     unknown       7.0  unknown
4    1/7/2017        32.0   unknown     Rain
5    1/8/2017     unknown   unknown    Sunny
6    1/9/2017     unknown   unknown  unknown
7   1/10/2017        34.0       8.0   Cloudy
8   1/11/2017        -4.0      -1.0     Snow
9   1/12/2017        26.0      12.0    Sunny
10  1/13/2017        12.0      12.0    Rainy
11  1/11/2017        -1.0      12.0     Snow
12  1/14/2017        40.0      -1.0    Sunny

In [23]:
# Fill missing values with mean
filled_mean = df_weather.fillna(df_weather.mean(numeric_only = True))
filled_mean

          day  temperature  windspeed   event
0    1/1/2017    32.000000   6.000000    Rain
1    1/4/2017    18.888889   9.000000   Sunny
2    1/5/2017    -1.000000   7.111111    Snow
3    1/6/2017    18.888889   7.000000     NaN
4    1/7/2017    32.000000   7.111111    Rain
5    1/8/2017    18.888889   7.111111   Sunny
6    1/9/2017    18.888889   7.111111     NaN
7   1/10/2017    34.000000   8.000000  Cloudy
8   1/11/2017    -4.000000  -1.000000    Snow
9   1/12/2017    26.000000  12.000000   Sunny
10  1/13/2017    12.000000  12.000000   Rainy
11  1/11/2017    -1.000000  12.000000    Snow
12  1/14/2017    40.000000  -1.000000   Sunny

In [31]:
temp_mean =df_weather['temperature'].mean()
temp_mean

np.float64(18.88888888888889)

In [33]:
df_weather['temperature'] = df_weather['temperature'].fillna(temp_mean)
df_weather

          day  temperature  windspeed   event
0    1/1/2017    32.000000        6.0    Rain
1    1/4/2017    18.888889        9.0   Sunny
2    1/5/2017    -1.000000        NaN    Snow
3    1/6/2017    18.888889        7.0     NaN
4    1/7/2017    32.000000        NaN    Rain
5    1/8/2017    18.888889        NaN   Sunny
6    1/9/2017    18.888889        NaN     NaN
7   1/10/2017    34.000000        8.0  Cloudy
8   1/11/2017    -4.000000       -1.0    Snow
9   1/12/2017    26.000000       12.0   Sunny
10  1/13/2017    12.000000       12.0   Rainy
11  1/11/2017    -1.000000       12.0    Snow
12  1/14/2017    40.000000       -1.0   Sunny

In [34]:
df_weather['windspeed'] = df_weather['windspeed'].fillna(df_weather['windspeed'].median())
df_weather

          day  temperature  windspeed   event
0    1/1/2017    32.000000        6.0    Rain
1    1/4/2017    18.888889        9.0   Sunny
2    1/5/2017    -1.000000        8.0    Snow
3    1/6/2017    18.888889        7.0     NaN
4    1/7/2017    32.000000        8.0    Rain
5    1/8/2017    18.888889        8.0   Sunny
6    1/9/2017    18.888889        8.0     NaN
7   1/10/2017    34.000000        8.0  Cloudy
8   1/11/2017    -4.000000       -1.0    Snow
9   1/12/2017    26.000000       12.0   Sunny
10  1/13/2017    12.000000       12.0   Rainy
11  1/11/2017    -1.000000       12.0    Snow
12  1/14/2017    40.000000       -1.0   Sunny

In [37]:
mode_event = df_weather['event'].mode()[0]
mode_event

'Sunny'

In [38]:
filled_mode = df_weather.assign(
    event = df_weather['event'].fillna(mode_event)
)
filled_mode

          day  temperature  windspeed   event
0    1/1/2017    32.000000        6.0    Rain
1    1/4/2017    18.888889        9.0   Sunny
2    1/5/2017    -1.000000        8.0    Snow
3    1/6/2017    18.888889        7.0   Sunny
4    1/7/2017    32.000000        8.0    Rain
5    1/8/2017    18.888889        8.0   Sunny
6    1/9/2017    18.888889        8.0   Sunny
7   1/10/2017    34.000000        8.0  Cloudy
8   1/11/2017    -4.000000       -1.0    Snow
9   1/12/2017    26.000000       12.0   Sunny
10  1/13/2017    12.000000       12.0   Rainy
11  1/11/2017    -1.000000       12.0    Snow
12  1/14/2017    40.000000       -1.0   Sunny

In [41]:
dubllicate_rows_df = pd.read_csv(path, skiprows=1, header = 0, na_values={
    "temperature":['not available'],
    'windspeed': ['not measured'],
    'event': ['no event']
})

In [45]:
dubllicate_rows_df

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny
13  1/11/2017         -1.0       12.0    Snow
14  1/14/2017         40.0       -1.0   Sunny
15  1/11/2017         -1.0       12.0    Snow
16  1/14/2017         40.0       -1.0   Sunny
17  1/11/2017         -1.0       12.0    Snow
18  1/14/2017         40.0       -1.0   Sunny

In [46]:
# Detect duplicate rows
dubllicate_rows_df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14     True
15     True
16     True
17     True
18     True
dtype: bool

In [47]:
no_dublicated_row =dubllicate_rows_df.drop_duplicates()
no_dublicated_row

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [51]:
# Display the data type  of df
filled_mode.dtypes

day                str
temperature      int64
windspeed      float64
event              str
dtype: object

In [50]:
# Convert column data type
filled_mode['temperature'] = filled_mode['temperature'].astype("int")

In [52]:
# Rename DataFrame columns
df = filled_mode.rename(columns={
    "day": "Date"
})

df

         Date  temperature  windspeed   event
0    1/1/2017           32        6.0    Rain
1    1/4/2017           18        9.0   Sunny
2    1/5/2017           -1        8.0    Snow
3    1/6/2017           18        7.0   Sunny
4    1/7/2017           32        8.0    Rain
5    1/8/2017           18        8.0   Sunny
6    1/9/2017           18        8.0   Sunny
7   1/10/2017           34        8.0  Cloudy
8   1/11/2017           -4       -1.0    Snow
9   1/12/2017           26       12.0   Sunny
10  1/13/2017           12       12.0   Rainy
11  1/11/2017           -1       12.0    Snow
12  1/14/2017           40       -1.0   Sunny

In [53]:
df.to_csv('/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/cleaned_weather.csv')

## What is Data Transformation?

Data Transformation means:
- Modifying data structure
- Filtering useful records
- Sorting values
- Applying custom functions

This step is very important in:
- Data Analysis
- Machine Learning
- Data Preprocessing

## Dataset Information

We will use the automobile dataset: `imports-85.data`

This dataset contains:
- Car price
- Engine size
- Horsepower
- Fuel type
- Body style
- And other automobile features

In [1]:
# Import pandas library
import pandas as pd

# Import numpy library
import numpy as np

## Loading the Dataset

We will load the dataset using pandas.
This dataset has no header, so we will assign column names.

In [3]:
columns  = [
    "symboling", "normalized_losses", "make", "fuel_type", "aspiration",
    "num_of_doors", "body_style", "drive_wheels", "engine_location",
    "wheel_base", "length", "width", "height", "curb_weight",
    "engine_type", "num_of_cylinders", "engine_size", "fuel_system",
    "bore", "stroke", "compression_ratio", "horsepower",
    "peak_rpm", "city_mpg", "highway_mpg", "price"
]

In [4]:
# Load the dataset from file "imports-85.data" and # Assign appropriate column names to the dataset
df = pd.read_csv('/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/imports-85.data', header=None , names = columns)

# Display first 5 rows
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [5]:
# Display dataset shape

df.shape

(205, 26)

In [6]:
# Display column data types
df.dtypes

symboling              int64
normalized_losses        str
make                     str
fuel_type                str
aspiration               str
num_of_doors             str
body_style               str
drive_wheels             str
engine_location          str
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type              str
num_of_cylinders         str
engine_size            int64
fuel_system              str
bore                     str
stroke                   str
compression_ratio    float64
horsepower               str
peak_rpm                 str
city_mpg               int64
highway_mpg            int64
price                    str
dtype: object

In [7]:
# Display basic information about dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized_losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel_type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num_of_doors       205 non-null    str
 6   body_style         205 non-null    str
 7   drive_wheels       205 non-null    str
 8   engine_location    205 non-null    str
 9   wheel_base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb_weight        205 non-null    int64
 14  engine_type        205 non-null    str
 15  num_of_cylinders   205 non-null    str
 16  engine_size        205 non-null    int64
 17  fuel_system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression_ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak_rpm           205 non-null    str
 23  city_mpg           205 non-null    int64
 24  highway_mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

## Handling Missing Values Note

Earlier we discussed missing data in NumPy.  
Now, in Pandas we handle missing values more effectively using:
- isnull()
- fillna()
- dropna()

In [ ]:
numeric_cols = ['price', 'horsepower', 'engine_size', 'city_mpg','highway_mpg']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors = "coerce")

In [13]:
df.replace("?",np.nan, inplace = True)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625.0

In [10]:
df.isnull().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_of_doors          2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_of_cylinders      0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

## Sorting Data

Sorting helps to:
- Identify highest and lowest values
- Organize data for analysis

In [14]:
# Sort the dataset based on price column (ascending)
sorted_price_asc = df.sort_values(by = "price", ascending= True)
sorted_price_asc

# Sort the dataset based on price column (descending)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
138,2,83,subaru,gas,std,two,hatchback,fwd,front,93.7,...,97,2bbl,3.62,2.36,9.0,69.0,4900,31,36,5118.0
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48.0,5100,47,53,5151.0
50,1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.0,68.0,5000,30,31,5195.0
150,1,87,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800,35,39,5348.0
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.4,68.0,5500,37,41,5389.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,1,NaN,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184.0,4500,14,16,45400.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400,38,43,NaN
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750,17,28,NaN

In [15]:
# Sort dataset using multiple columns (e.g., horsepower and price)
sorted_multi = df.sort_values(by =['horsepower', 'price'], ascending= [False, False])
sorted_multi.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750,17,28,NaN
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262.0,5000,13,17,36000.0
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,37028.0
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,34028.0
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,32528.0

## Filtering Data

Filtering allows us to:
- Select rows based on conditions
- Analyze specific subsets of data

In [16]:
# Filter cars with price greater than a certain value
high_price_cars = df[df['price'] > 20000]
high_price_cars.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875.0
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970.0
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121.0,4250,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,30760.0

In [17]:
# Filter cars where fuel type is 'gas' and price is above a threshold
filtered_cars = df [ (df['fuel_type'] == 'gas') & (df['price'] > 20000)]
filtered_cars.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875.0
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970.0
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121.0,4250,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,30760.0

In [19]:
# Filter dataset and display only selected columns (e.g., price and horsepower)
selected = df[df['price'] > 15000][['price','horsepower', 'make']]
selected.head()

     price  horsepower         make
1  16500.0       111.0  alfa-romero
2  16500.0       154.0  alfa-romero
4  17450.0       115.0         audi
5  15250.0       110.0         audi
6  17710.0       110.0         audi

## Applying Functions

Pandas allows applying custom functions using:
- apply()
- map()
- lambda functions

This is useful for feature transformation.

In [20]:
# Apply a custom function to transform the price column
def price_in_thousands(x):
    if pd.notnull(x):
        return x / 1000
    return x 

df["price_in_thousands"] = df['price'].apply(price_in_thousands)

df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,price_in_thousands
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495.0,13.495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500.0,16.500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154.0,5000,19,26,16500.0,16.500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950.0,13.950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450.0,17.450

In [21]:
# Use lambda function to modify a numeric column (e.g., scaling price)
df['horsepower_scaled'] = df['horsepower'].apply(lambda x: x * 1.1 if pd.notnull(x) else x)

df[['horsepower', 'horsepower_scaled']].head()

   horsepower  horsepower_scaled
0       111.0              122.1
1       111.0              122.1
2       154.0              169.4
3       102.0              112.2
4       115.0              126.5

## Creating New Columns

We can create new columns based on existing data.
This is commonly used in data preprocessing.

In [22]:
# Create a new column such as price_category based on price values
def price_category(price):
    if pd.isnull(price):
        return "Unknown"
    elif price <  10000:
        return "Low"
    elif price < 20000:
        return "Medium"
    else: 
        return "High"
    
    
df['price_category'] = df['price'].apply(price_category)

df[['price', 'price_category']].head()

     price price_category
0  13495.0         Medium
1  16500.0         Medium
2  16500.0         Medium
3  13950.0         Medium
4  17450.0         Medium

In [24]:
df['fuel_type'].unique()

<StringArray>
['gas', 'diesel']
Length: 2, dtype: str

In [26]:
# Convert categorical values (e.g., fuel type) into numerical form using mapping
fuel_map = {'gas': 0, 'diesel': 1}

df['fuel_encode'] = df['fuel_type'].map(fuel_map)

df[['fuel_type', 'fuel_encode']].head()

  fuel_type  fuel_encode
0       gas            0
1       gas            0
2       gas            0
3       gas            0
4       gas            0

## Group-Based Transformation

Grouping helps to analyze data category-wise.
Example:
- Average price per fuel type
- Average horsepower per body style

In [20]:
# Check missing values in the dataset


# Count missing values per column

Transform the dataset to:
- Filter expensive cars
- Sort by horsepower
- Create a performance category column

In [ ]:
# Filter high price cars
# 25000 > filter 


# Sort them by horsepower descending order 


# Create a new derived column based on engine size or price
 # engine size < 120 - low performance
 # engine size < 200 - medium performance  
# up then High performance


# make , price, horsepower, engine size , performance_category