## What is Grouping in Pandas?

Grouping means:
- Splitting data into groups based on some category
- Applying calculations on each group
- Combining results into summarized insights

In Pandas, grouping is done using:
groupby()

This follows the concept:
Split → Apply → Combine

## Real-Life Examples of Grouping

Grouping is widely used in:
- Business Analytics (sales by region)
- Education (marks by subject)
- Finance (expenses by category)
- Automotive Analysis (price by car brand)

For example:
Instead of analyzing 200 cars individually,
we can analyze:
Average price per car manufacturer.

Pandas groupby() is an essential method for data aggregation and analysis in python. It follows the "Split-Apply-Combine" pattern, which means it allows users to −

- Split data into groups based on specific criteria.
- Apply functions independently to each group.
- Combine the results into a structured format.

Every groupby() operation involves three key steps, splitting data into groups based on some criteria, apply functions independently to each group, and then merge the results back into a meaningful structure.

In many situations, we apply some functions on each splitted groups. In the apply functionality, we can perform the following operations −

- Aggregation: Computing summary statistics like mean, sum, etc.
- Transformation: Applying a function to transform data.
- Filtration: Removing groups based on some condition.

In [1]:
# Import pandas library
import pandas as pd


# Import numpy library
import numpy as np

In [2]:
# Load the dataset using pandas
df_car = pd.read_csv('/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/cars_details.csv')


# Display first 5 rows
df_car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [3]:
df_car.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='str')

In [4]:
df_car.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
dtypes: int64(3), str(5)
memory usage: 271.4 KB

## Understanding groupby() Function

The groupby() function is used to:
- Group rows based on a categorical column
- Perform aggregation operations on each group

Syntax:
df.groupby("column_name")

In [5]:
# Group the dataset by a categorical column (e.g., fuel)
fuel_group = df_car.groupby("fuel")
fuel_group

In [7]:
fuel_group.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
17,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
22,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
27,Hyundai Venue SX Opt Diesel,2019,1195000,5000,Diesel,Dealer,Manual,First Owner
157,Maruti Wagon R DUO LPG,2014,210000,90000,LPG,Individual,Manual,First Owner
176,Maruti Alto K10 LXI CNG,2020,282000,40000,CNG,Individual,Manual,First Owner
222,Maruti Omni LPG CARGO BSIII W IMMOBILISER,2009,80000,90000,LPG,Individual,Manual,Second Owner
351,Tata Indigo CS Emax CNG GLX,2014,185000,72000,CNG,Dealer,Manual,First Owner
352,Maruti Eeco 5 STR With AC Plus HTR CNG,2012,229999,75000,CNG,Dealer,Manual,First Owner
483,Hyundai EON LPG Magna Plus,2012,180000,90000,LPG,Individual,Manual,First Owner
495,Hyundai Santro Xing GLS Audio LPG,2012,250000,100000,LPG,Individual,Manual,First Owner
657,Hyundai i10 Magna LPG,2013,250000,88600,LPG,Individual,Manual,First Owner
4145,Toyota Camry Hybrid,2006,310000,62000,Electric,Dealer,Automatic,Second Owner

## Aggregation in Pandas

Aggregation means applying statistical functions such as:
- sum()
- mean()
- median()
- min()
- max()
- count()

These help summarize large datasets efficiently.

In [8]:
# Calculate mean of numerical columns after grouping
mean_by_fuel = fuel_group[['selling_price', 'km_driven']].mean()
mean_by_fuel

          selling_price     km_driven
fuel
CNG       277174.925000  67234.750000
Diesel    669094.252206  79630.977706
Electric  310000.000000  62000.000000
LPG       167826.043478  89634.782609
Petrol    344840.137541  52340.079604

In [9]:
# Apply multiple aggregation functions (mean, max, min)
agg_multiple = fuel_group['selling_price'].agg(['mean', 'max', 'min', 'count'])
agg_multiple

                   mean      max     min  count
fuel
CNG       277174.925000   595000   45000     40
Diesel    669094.252206  8150000   45000   2153
Electric  310000.000000   310000  310000      1
LPG       167826.043478   290000   50000     23
Petrol    344840.137541  8900000   20000   2123

## Grouping by Multiple Columns

We can group data using more than one categorical column.

Example:
Group by:
- fuel
- owner

This creates hierarchical grouping.

In [20]:
# Group dataset by multiple columns
pd.set_option('display.float_format', '{:.2f}'.format)

multi_group = df_car.groupby(['fuel', 'owner'])

multi_group_mean = multi_group['selling_price'].mean()

multi_group_mean

fuel      owner
CNG       First Owner             372809.38
          Fourth & Above Owner    108333.33
          Second Owner            191642.86
          Third Owner             125000.00
Diesel    First Owner             793441.57
          Fourth & Above Owner    243823.47
          Second Owner            458065.17
          Test Drive Car         1056285.57
          Third Owner             371999.96
Electric  Second Owner            310000.00
LPG       First Owner             211000.00
          Fourth & Above Owner     60000.00
          Second Owner            141999.90
          Third Owner             135000.00
Petrol    First Owner             409025.73
          Fourth & Above Owner    125837.19
          Second Owner            232662.70
          Test Drive Car          882899.80
          Third Owner             162278.50
Name: selling_price, dtype: float64

## Selecting Specific Columns After Grouping

Instead of aggregating the whole dataset,
we can select specific numerical columns for analysis.
This improves clarity and performance.

In [21]:
# Group by a category and aggregate only selected column
fuel_group = df_car.groupby("fuel")[['selling_price', 'year', 'km_driven']].mean()
fuel_group

          selling_price    year  km_driven
fuel
CNG           277174.92 2013.47   67234.75
Diesel        669094.25 2013.61   79630.98
Electric      310000.00 2006.00   62000.00
LPG           167826.04 2010.13   89634.78
Petrol        344840.14 2012.60   52340.08

## Group Size and Counting Records

Sometimes we want to know:
- Number of records per group
- Frequency of categories

This helps in understanding data distribution.

In [24]:
# Count number of records in each group
group_counts = df_car.groupby("transmission").size()
group_counts

transmission
Automatic     448
Manual       3892
dtype: int64

## Using agg() Function (Advanced Aggregation)

The agg() function allows:
- Applying multiple operations at once
- Custom aggregation logic
- Better summarized reports

In [25]:
# Use agg() to calculate multiple statistics per group
adv_agg = df_car.groupby("fuel").agg(
    {
        "selling_price": ['mean', 'max','min'],
        "km_driven": ['mean', 'max'],
        "year": ["mean"]
    }
)


adv_agg

         selling_price                  km_driven            year
                  mean      max     min      mean     max    mean
fuel
CNG          277174.92   595000   45000  67234.75  120000 2013.47
Diesel       669094.25  8150000   45000  79630.98  560000 2013.61
Electric     310000.00   310000  310000  62000.00   62000 2006.00
LPG          167826.04   290000   50000  89634.78  170000 2010.13
Petrol       344840.14  8900000   20000  52340.08  806599 2012.60

## Transform vs Aggregate (Important Concept)

Aggregation:
- Reduces data size
- Produces summary values

Transform:
- Keeps original data size
- Applies group-wise calculations

This is very important in feature engineering.

In [26]:
df_car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [27]:
# Apply group-wise transformation on a numerical column

df_car['avg_sell_price'] = df_car.groupby("fuel")['selling_price'].transform("mean")

#display relevant columns 
df_car[['fuel', 'selling_price', 'avg_sell_price']].head()

     fuel  selling_price  avg_sell_price
0  Petrol          60000       344840.14
1  Petrol         135000       344840.14
2  Diesel         600000       669094.25
3  Petrol         250000       344840.14
4  Diesel         450000       669094.25

In [28]:
df_car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,avg_sell_price
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,344840.14
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,344840.14
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,344840.14
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25

## Filtering Groups

We can filter entire groups based on a condition.
Example:
- Only show groups with average price > threshold

In [33]:
# Filter grouped data based on a condition
filter_group = df_car.groupby("fuel").filter(
    lambda x:x['selling_price'] .mean()> 500000
)
filter_group

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,avg_sell_price
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25
17,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25
27,Hyundai Venue SX Opt Diesel,2019,1195000,5000,Diesel,Dealer,Manual,First Owner,669094.25
...,...,...,...,...,...,...,...,...,...
4333,Maruti Ritz VDi,2012,225000,90000,Diesel,Individual,Manual,Second Owner,669094.25
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner,669094.25
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,669094.25
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,669094.25
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,669094.25

## Sorting Grouped Results

After aggregation, results can be sorted to:
- Identify top categories
- Find highest or lowest performing groups

In [37]:
# Sort grouped aggregation results by a numerical metric
sorted_df = df_car.groupby("owner")['selling_price'].mean().sort_values(ascending= False)
sorted_df

owner
Test Drive Car         954293.94
First Owner            598636.97
Second Owner           343891.09
Third Owner            269474.00
Fourth & Above Owner   173901.20
Name: selling_price, dtype: float64

## Real-World Insight Generation

Grouping helps answer real analytical questions such as:
- Which car brand has highest average price?
- Which fuel type,brand  has best avg price?

This is the foundation of:
- Exploratory Data Analysis (EDA)
- Business Intelligence
- Machine Learning feature analysis

In [38]:
df_car

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,avg_sell_price
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,344840.14
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,344840.14
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,344840.14
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,669094.25
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,669094.25
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,344840.14
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,669094.25
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,344840.14

In [39]:
df = df_car.copy()

In [40]:
df['strip_car_name'] = df['name'].str.strip()
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,avg_sell_price,strip_car_name
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,344840.14,Maruti 800 AC
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,344840.14,Maruti Wagon R LXI Minor
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25,Hyundai Verna 1.6 SX
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,344840.14,Datsun RediGO T Option
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25,Honda Amaze VX i-DTEC

In [41]:
df['brand'] = df['strip_car_name'].str.split(' ').str[0]

In [42]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,avg_sell_price,strip_car_name,brand
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,344840.14,Maruti 800 AC,Maruti
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,344840.14,Maruti Wagon R LXI Minor,Maruti
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,669094.25,Hyundai Verna 1.6 SX,Hyundai
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,344840.14,Datsun RediGO T Option,Datsun
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,669094.25,Honda Amaze VX i-DTEC,Honda

In [13]:
# Group dataset by a categorical feature


# Calculate mean price and horsepower


# Sort the results


# Display top performing groups

In [43]:
sorted_df.reset_index()

                  owner  selling_price
0        Test Drive Car      954293.94
1           First Owner      598636.97
2          Second Owner      343891.09
3           Third Owner      269474.00
4  Fourth & Above Owner      173901.20

## Common Mistakes in Grouping (Important)

1. Grouping without cleaning missing values  
2. Aggregating non-numeric columns  
3. Forgetting reset_index() after groupby  
4. Misinterpreting grouped results  

Always inspect grouped data carefully.

1. Which fuel type has highest average resale price?
2. Do automatic cars sell for more than manual cars?
3. Which year group (older vs newer) has higher average price?
4. Which seller type dominates the dataset?