## What is loc?

loc is used for label-based indexing in Pandas.

It allows us to:
- Select rows by index labels
- Select columns by column names
- Perform conditional filtering

Syntax:
df.loc[row_label, column_label]

In [1]:
# Import pandas library
import pandas as pd


# Import numpy library
import numpy as np

In [2]:
# Load your dataset (e.g., car dataset or CSV file)
df = pd.read_csv("/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/cars_details.csv")


# Display first 5 rows
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [3]:
df.shape

(4340, 8)

In [4]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
dtypes: int64(3), str(5)
memory usage: 271.4 KB

In [8]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [9]:
df.describe()

         year  selling_price  km_driven
count 4340.00        4340.00    4340.00
mean  2013.09      504127.31   66215.78
std      4.22      578548.74   46644.10
min   1992.00       20000.00       1.00
25%   2011.00      208749.75   35000.00
50%   2014.00      350000.00   60000.00
75%   2016.00      600000.00   90000.00
max   2020.00     8900000.00  806599.00

In [13]:
df.describe(include = 'all')

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
count,4340,4340.00,4340.00,4340.00,4340,4340,4340,4340
unique,1491,NaN,NaN,NaN,5,3,2,5
top,Maruti Swift Dzire VDI,NaN,NaN,NaN,Diesel,Individual,Manual,First Owner
freq,69,NaN,NaN,NaN,2153,3244,3892,2832
mean,NaN,2013.09,504127.31,66215.78,NaN,NaN,NaN,NaN
std,NaN,4.22,578548.74,46644.10,NaN,NaN,NaN,NaN
min,NaN,1992.00,20000.00,1.00,NaN,NaN,NaN,NaN
25%,NaN,2011.00,208749.75,35000.00,NaN,NaN,NaN,NaN
50%,NaN,2014.00,350000.00,60000.00,NaN,NaN,NaN,NaN
75%,NaN,2016.00,600000.00,90000.00,NaN,NaN,NaN,NaN
max,NaN,2020.00,8900000.00,806599.00,NaN,NaN,NaN,NaN

## Selecting Rows using loc

loc selects rows based on index labels, not position.

In [14]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [17]:
df_with_index = df.set_index('name')
df_with_index

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
name,,,,,,,
Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [27]:
student_data = pd.read_json("/home/fm-pc-lt-269/Desktop/data_science/notebooks/pandas/data/students.json")
student_data =student_data.set_index('Name')

In [28]:
student_data

       StudentID   Age  Course  Score
Name
Ram            1 21.00  Python  85.00
Sita           2 22.00      DS  90.00
Hari           3   NaN      AI  88.00
Gita           4 23.00     NaN    NaN
Nabin          5 24.00      ML  92.00
Nabin          5 24.00      ML  92.00

In [29]:
# Select a single row using loc
row_0 = student_data.loc['Ram']
row_0

StudentID         1
Age           21.00
Course       Python
Score         85.00
Name: Ram, dtype: object

In [30]:
# Select multiple rows using loc
multi_row = student_data['Ram':'Gita']
multi_row

      StudentID   Age  Course  Score
Name
Ram           1 21.00  Python  85.00
Sita          2 22.00      DS  90.00
Hari          3   NaN      AI  88.00
Gita          4 23.00     NaN    NaN

## Selecting Columns using loc

We can also select specific columns using column labels.

In [31]:
# Select specific columns using loc
select_cols = student_data.loc[:,['Age',"Course"]]
select_cols

        Age  Course
Name
Ram   21.00  Python
Sita  22.00      DS
Hari    NaN      AI
Gita  23.00     NaN
Nabin 24.00      ML
Nabin 24.00      ML

In [32]:
# Select specific columns using loc
select_cols = student_data.loc['Ram':'Gita',['Age',"Course"]]
select_cols

       Age  Course
Name
Ram  21.00  Python
Sita 22.00      DS
Hari   NaN      AI
Gita 23.00     NaN

In [33]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [35]:
# Filter dataset using a condition with loc (e.g., price > threshold)
high_price = df.loc[df['selling_price'] > 5000000]
high_price

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner

In [36]:
filter_multi = df.loc[
    (df['fuel'] == "Petrol") & (df['transmission'] == "Manual")
]
filter_multi

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

## What is iloc?

iloc is used for integer position-based indexing.

It selects data based on:
- Row position (0,1,2…)
- Column position (0,1,2…)

Syntax:
df.iloc[row_index, column_index]

## Difference Between loc and iloc

| Feature | loc | iloc |
|--------|-----|------|
| Basis | Labels | Positions |
| Input | Index names | Integer index |
| Usage | Named selection | Numeric selection |

In [37]:
# Select a single row using iloc
row_iloc = student_data.iloc[0]
row_iloc

StudentID         1
Age           21.00
Course       Python
Score         85.00
Name: Ram, dtype: object

In [39]:
# Select specific columns using iloc
row_iloc = df.iloc[0:9]
row_iloc

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner

In [40]:
# Slice rows and columns using iloc
sliced = df.iloc[:5, 0:3]
sliced

                       name  year  selling_price
0             Maruti 800 AC  2007          60000
1  Maruti Wagon R LXI Minor  2007         135000
2      Hyundai Verna 1.6 SX  2012         600000
3    Datsun RediGO T Option  2017         250000
4     Honda Amaze VX i-DTEC  2014         450000

# Merging, Joining, and Concatenating DataFrames in Pandas

In real-world data analysis, data is rarely stored in a single file.
Instead, data is often distributed across:
- Multiple CSV files
- Different Excel sheets
- Various databases
- APIs and logs

To perform proper analysis, we must combine multiple datasets.
This process is called:
- Merging
- Joining
- Concatenation

## Why Combining DataFrames is Important?

In real-life scenarios:
- Sales data may be in one file
- Customer data in another file
- Product data in a separate file

To analyze complete information, we need to combine these datasets.

This is widely used in:
- Business Analytics
- Machine Learning pipelines
- Data Engineering workflows
- Data Cleaning & EDA

## Three Main Ways to Combine Data in Pandas

1. Concatenation (concat) → Stack DataFrames vertically or horizontally  
2. Merging (merge) → Combine based on common keys (like SQL JOIN)  
3. Joining (join) → Combine DataFrames based on index  

Each method serves a different purpose.

## What is Concatenation?

Concatenation means:
- Stacking DataFrames together
- Along rows (vertical)
- Along columns (horizontal)

It is useful when:
- Data is split across multiple files
- Monthly datasets need to be combined

In [ ]:
# Import pandas library


# Import numpy library

We will create multiple DataFrames to simulate real-world datasets

such as sales data from different months.

In [41]:
# Create first DataFrame (e.g., Month 1 data)
df_1 = pd.DataFrame({
    "Id": [1,2,3],
    "Name": ["Maruti", "hyundai", "Honda"],
    "Price": [300000,400000,500000]
})

# Create second DataFrame (e.g., Month 2 data)
df_2 = pd.DataFrame({
    "Id": [4,5,6],
    "Name": ["Suzuki", "Toyota", "Ford"],
    "Price": [400000,300000,600000]
})

df_1, df_2

(   Id     Name   Price
 0   1   Maruti  300000
 1   2  hyundai  400000
 2   3    Honda  500000,
    Id    Name   Price
 0   4  Suzuki  400000
 1   5  Toyota  300000
 2   6    Ford  600000)

Vertical concatenation stacks DataFrames on top of each other.

Used when columns are the same but rows are different.

In [42]:
# Concatenate DataFrames vertically
vertical_concat = pd.concat([df_1,df_2], axis = 0)
vertical_concat

   Id     Name   Price
0   1   Maruti  300000
1   2  hyundai  400000
2   3    Honda  500000
0   4   Suzuki  400000
1   5   Toyota  300000
2   6     Ford  600000

Horizontal concatenation combines DataFrames side by side.

Used when rows represent the same entities but columns differ.

In [44]:
# Concatenate DataFrames horizontally
df_f = pd.DataFrame({
    "Mileage":[20,16,17],
    "Fuel":["Petrol", "Diesel","Petrol"]
})

horizonatal_concat = pd.concat(
    [df_1, df_f], axis = 1
    )
horizonatal_concat

   Id     Name   Price  Mileage    Fuel
0   1   Maruti  300000       20  Petrol
1   2  hyundai  400000       16  Diesel
2   3    Honda  500000       17  Petrol

## What is Merging?

Merging is similar to SQL JOIN operations.

It combines two DataFrames based on a common column (key).
Example:
- Student Data (ID, Name)
- Marks Data (ID, Score)

We merge them using the common key: ID

## Types of Merge Operations in Pandas

1. Inner Merge → Only matching records
2. Left Merge → All records from left + matches from right
3. Right Merge → All records from right + matches from left
4. Outer Merge → All records from both DataFrames

In [45]:
df_1 = pd.DataFrame({
    "Id": [1,2,3],
    "Name": ["Maruti", "hyundai", "Honda"],
    "Price": [300000,400000,500000]
})

# Create second DataFrame (e.g., Month 2 data)
df_2 = pd.DataFrame({
    "Id": [1,2,5],
    "Mileage":[20,16,17],
    "Fuel":["Petrol", "Diesel","Petrol"]
    
})

In [47]:
df_1

   Id     Name   Price
0   1   Maruti  300000
1   2  hyundai  400000
2   3    Honda  500000

In [48]:
df_2

   Id  Mileage    Fuel
0   1       20  Petrol
1   2       16  Diesel
2   5       17  Petrol

Inner merge returns only the rows where keys exist in both DataFrames.

In [46]:
# Merge two DataFrames using inner join on common key
inner_merge = pd.merge(df_1,df_2, on = "Id", how = "inner")
inner_merge

   Id     Name   Price  Mileage    Fuel
0   1   Maruti  300000       20  Petrol
1   2  hyundai  400000       16  Diesel

Left merge keeps all rows from the left DataFrame

and matches rows from the right DataFrame when available.

In [49]:
# Perform left merge using a common key
left_merge = pd.merge(df_1, df_2, on = "Id", how = "left")
left_merge

   Id     Name   Price  Mileage    Fuel
0   1   Maruti  300000    20.00  Petrol
1   2  hyundai  400000    16.00  Diesel
2   3    Honda  500000      NaN     NaN

Right merge keeps all rows from the right DataFrame

and matches rows from the left DataFrame when available.

In [50]:
# Perform right merge using a common key
right_merge = pd.merge(df_1,df_2, on = "Id", how = "right")
right_merge

   Id     Name     Price  Mileage    Fuel
0   1   Maruti 300000.00       20  Petrol
1   2  hyundai 400000.00       16  Diesel
2   5      NaN       NaN       17  Petrol

Outer merge returns all rows from both DataFrames.

Missing matches are filled with NaN values.

In [51]:
# Perform outer merge on the common key
outer_merge = pd.merge(df_1,df_2, on = "Id", how = "outer")
outer_merge

   Id     Name     Price  Mileage    Fuel
0   1   Maruti 300000.00    20.00  Petrol
1   2  hyundai 400000.00    16.00  Diesel
2   3    Honda 500000.00      NaN     NaN
3   5      NaN       NaN    17.00  Petrol

## What is Join in Pandas?

Join is used to combine DataFrames based on their index.
It is useful when:
- DataFrames share the same index
- We want faster merging using index alignment

In [55]:
# Set index for both DataFrames before joining
df_1

       Name   Price
Id
1    Maruti  300000
2   hyundai  400000
3     Honda  500000

In [56]:
df_2

    Mileage    Fuel
Id
1        20  Petrol
2        16  Diesel
5        17  Petrol

In [54]:
df_1 = df_1.set_index("Id")
df_2 = df_2.set_index("Id")

In [57]:
joined_df = df_1.join(df_2, how = "left")
joined_df

       Name   Price  Mileage    Fuel
Id
1    Maruti  300000    20.00  Petrol
2   hyundai  400000    16.00  Diesel
3     Honda  500000      NaN     NaN

In [ ]:
# Join two DataFrames using index

## Real-World Example

Suppose we have:
- Car details dataset
- Car price dataset
- Car usage dataset

We merge them to create a complete analytical dataset.
This process is called Data Integration.

In [ ]:
# Create multiple DataFrames representing different data sources


# Merge them into a single unified DataFrame

## Merge vs Join vs Concat (Key Differences)

| Method | Basis | Use Case |
|-------|------|----------|
| concat() | Axis (rows/columns) | Combine similar datasets |
| merge() | Common key column | SQL-like joins |
| join() | Index | Fast index-based merging |

## What is a Pivot Table?

A Pivot Table is used to summarize and aggregate data dynamically.

It helps to:
- Analyze relationships between variables
- Generate summary statistics
- Create analytical reports

Similar to Excel Pivot Tables.

## Why Pivot Tables are Important?

Pivot tables allow:
- Multi-dimensional aggregation
- Quick business insights
- Flexible data analysis

Widely used in:
- Sales analysis
- Financial reporting
- Market analytics
- EDA workflows

In [58]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [59]:
# Create a pivot table to summarize a numerical column by a category
pivot_fuel = pd.pivot_table(
    df,
    values = "selling_price",
    index ="fuel",
    aggfunc= "mean"
    
)
pivot_fuel

          selling_price
fuel
CNG           277174.92
Diesel        669094.25
Electric      310000.00
LPG           167826.04
Petrol        344840.14

In [60]:
# Create a pivot table to summarize a numerical column by a category
pivot_fuel = pd.pivot_table(
    df,
    values = "selling_price",
    index ="fuel",
    aggfunc= ['mean','max','count']
    
)
pivot_fuel

                  mean           max         count
         selling_price selling_price selling_price
fuel
CNG          277174.92        595000            40
Diesel       669094.25       8150000          2153
Electric     310000.00        310000             1
LPG          167826.04        290000            23
Petrol       344840.14       8900000          2123

In [61]:
# Create pivot table using multiple index and columns
pivot_fuel_transmission = pd.pivot_table(
    df,
    values ="selling_price",
    index = "fuel",
    columns = "transmission",
    aggfunc= "mean"
)
pivot_fuel_transmission

transmission  Automatic    Manual
fuel
CNG                 NaN 277174.92
Diesel       1900102.35 504441.25
Electric      310000.00       NaN
LPG                 NaN 167826.04
Petrol        766409.30 302683.22

## What is Crosstab?

Crosstab (Cross Tabulation) is used to:
- Calculate frequency counts
- Analyze relationships between categorical variables
- Create contingency tables

It is commonly used in:
- Survey analysis
- Market research
- Categorical data analysis

## Crosstab vs Pivot Table

| Feature | Pivot Table | Crosstab |
|--------|-------------|----------|
| Purpose | Aggregation | Frequency counts |
| Data Type | Numeric + Categorical | Mostly categorical |
| Flexibility | High | Simpler frequency analysis |

In [ ]:
# Create a crosstab between two categorical columns
crosstab = pd.crosstab(df['fuel'], df['transmission'])
crosstab

transmission  Automatic  Manual
fuel
CNG                   0      40
Diesel              254    1899
Electric              1       0
LPG                   0      23
Petrol              193    1930

In [64]:
seller = pd.crosstab(
    df['seller_type'],
    df['owner']
)
seller

owner,First Owner,Fourth & Above Owner,Second Owner,Test Drive Car,Third Owner
seller_type,,,,,
Dealer,844,2,122,17,9
Individual,1890,79,980,0,295
Trustmark Dealer,98,0,4,0,0

In [66]:
# Create crosstab with normalization or aggregation
price = pd.crosstab(
    df['fuel'],
    df["transmission"],
    values = df['selling_price'],
    aggfunc="mean"
)
price

transmission  Automatic    Manual
fuel
CNG                 NaN 277174.92
Diesel       1900102.35 504441.25
Electric      310000.00       NaN
LPG                 NaN 167826.04
Petrol        766409.30 302683.22